// UI
export const SET_LOADING = 'SET_LOADING';
export const CLEAR_LOADING = 'CLEAR_LOADING';

// USER
export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';

// TABLE
export const ADD_TABLE = 'ADD_TABLE';
export const REMOVE_TABLE = 'REMOVE_TABLE';
export const CACHE_TABLE_FILTER_VALUES = 'CACHE_TABLE_FILTER_VALUES';
export const UPDATE_TABLE_PAGINATION = 'UPDATE_TABLE_PAGINATION';

// FORM
export const ADD_FORM = 'ADD_FORM';
export const UPDATE_FORM = 'COMMON_UPDATE_FORM';
export const REMOVE_FORM = 'REMOVE_FORM';
