// CATEGORIES
export const HCHAIR_SET_CATEGORY = 'HCHAIR SET CATEGORY 2B';
export const HCHAIR_UPDATE_CATEGORY_FORM = 'HCHAIR UPDATE CATEGORY FORM 2B';
export const HCHAIR_SET_CATEGORIES = 'HCHAIR SET CATEGORIES 2B';
export const HCHAIR_SET_EXPANDED_CATEGORY = 'HCHAIR SET EXPANDED CATEGORY 2B';
export const HCHAIR_SET_ROOT_CATEGORY_ID = 'HCHAIR SET ROOT CATEGORY ID';

// CATEGORYX
export const HCHAIR_UPDATE_CATEGORY_FILTER = 'HCHAIR_UPDATE_CATEGORY_FILTER';
export const HCHAIR_SET_LEVEL_ONE_CATEGORY = 'HCHAIR_SET_LEVEL_ONE_CATEGORY';
export const HCHAIR_SET_LEVEL_THREE_CATEGORY = 'HCHAIR_SET_LEVEL_THREE_CATEGORY';
export const HCHAIR_RESET_CATEGORY_STATE = 'HCHAIR_RESET_CATEGORY_STATE';
export const HCHAIR_SET_SELECTED_PARENT_CATEGORY_ID = 'HCHAIR_SET_SELECTED_PARENT_CATEGORY_ID';
export const HCHAIR_SET_SELECTED_CATEGORY = 'HCHAIR_SET_SELECTED_CATEGORY';

// MEMBERS
export const HCHAIR_SET_MEMBER = 'HCHAIR SET MEMBER 2B';
export const HCHAIR_SET_MEMBER_FORM = 'HCHAIR SET MEMBER FORM 2B';
export const HCHAIR_UPDATE_MEMBER_FORM = 'HCHAIR UPDATE MEMBER FORM 2B';
export const HCHAIR_SET_MEMBER_LIST = 'HCHAIR SET MEMBER LIST 2B';
export const HCHAIR_SET_MEMBER_DETAILS = 'HCHAIR SET MEMBER DETAILS 2B';
export const HCHAIR_SET_PRODUCT_RATES = 'HCHAIR SET PRODUCT RATES 2B';
export const HCHAIR_SET_PRODUCT_RATE = 'HCHAIR SET PRODUCT RATE 2B';
export const HCHAIR_SET_PRODUCT_RATE_STATES = 'HCHAIR SET PRODUCT RATE STATES 2B';
export const HCHAIR_RESET_MEMBER_STATE = 'HCHAIR RESET MEMBER STATE 2B';
export const HCHAIR_RESET_MEMBER_DETAILS = 'HCHAIR RESET MEMBER DETAILS 2B';




// MERCHANTS
export const HCHAIR_SET_MERCHANT = 'HCHAIR SET MERCHANT 2B';
export const HCHAIR_SET_MERCHANT_FORM = 'HCHAIR SET MERCHANT FORM 2B';
export const HCHAIR_UPDATE_MERCHANT_FORM = 'HCHAIR UPDATE MERCHANT FORM 2B';

export const HCHAIR_SET_MERCHANT_LIST = 'HCHAIR SET MERCHANT LIST 2B';
export const HCHAIR_SET_MERCHANT_DETAILS = 'HCHAIR SET MERCHANT DETAILS 2B';


// PRODUCTS
// export const HCHAIR_SET_PRODUCT = 'HCHAIR SET PRODUCT 2B';
export const HCHAIR_SET_PRODUCT_FORM = 'HCHAIR SET PRODUCT FORM 2B';
// export const HCHAIR_UPDATE_PRODUCT_FORM = 'HCHAIR UPDATE PRODUCT FORM 2B';
export const HCHAIR_ENABLE_PRICE_TIER = 'HCHAIR ENABLE PRICE TIER 2B';

export const HCHAIR_SET_PRODUCT = 'HCHAIR_SET_PRODUCT';
export const HCHAIR_UPDATE_PRODUCT_FORM = 'HCHAIR_UPDATE_PRODUCT_FORM';
export const HCHAIR_SET_PRODUCT_LIST = 'HCHAIR_SET_PRODUCT_LIST';
export const HCHAIR_SET_PRODUCT_DETAILS = 'HCHAIR_SET_PRODUCT_DETAILS_2C';
export const HCHAIR_RESET_PRODUCT_STATE = 'HCHAIR_RESET_PRODUCT_STATE_2C';
export const HCHAIR_SET_PRODUCT_MERCHANT_RECOMMENDATION = 'HCHAIR_SET_PRODUCT_MERCHANT_RECOMMENDATION';
export const HCHAIR_SET_PRODUCT_MARKETPLACE_RECOMMENDATION = 'HCHAIR_SET_PRODUCT_MARKETPLACE_RECOMMENDATION';
export const HCHAIR_SET_MERCHANT_DELIVERY_OPTION = 'HCHAIR_SET_MERCHANT_DELIVERY_OPTION';
export const HCHAIR_SET_PRODUCT_DELIVERY_OPTION_OVERRIDE = 'HCHAIR_SET_PRODUCT_DELIVERY_OPTION_OVERRIDE';
export const HCHAIR_RESET_PRODUCT_DETAILS = 'HCHAIR_RESET_PRODUCT_DETAILS';
export const HCHAIR_ADD_NEW_DELIVERY_OPTION_OVERRIDE = 'HCHAIR_ADD_NEW_DELIVERY_OPTION_OVERRIDE';


// ORDERS
export const HCHAIR_SET_ORDER_DETAIL = 'HCHAIR SET_ORDER_DETAIL 2B';
// export const HCHAIR_UPDATE_ORDER_FILTER = 'HCHAIR UPDATE_ORDER_FILTER 2B';
export const HCHAIR_UPDATE_HEADER_TAB_INDEX = 'HCHAIR UPDATE_HEADER_TAB_INDEX 2B';
//
export const HCHAIR_UPDATE_ORDER_FILTER = 'HCHAIR UPDATE ORDER FILTER 2B';
export const HCHAIR_SET_ORDER_LIST = 'HCHAIR SET ORDER LIST 2B';
export const HCHAIR_UPDATE_ORDER_LIST_PAGINATION = 'HCHAIR UPDATE ORDER LIST PAGINATION 2B';
export const HCHAIR_SET_ORDER_PRODUCT_LIST = 'HCHAIR SET ORDER PRODUCT LIST 2B';
export const HCHAIR_SET_ORDER_DETAILS = 'HCHAIR SET ORDER DETAILS 2B';
export const HCHAIR_RESET_ORDER_STATE = 'HCHAIR RESET ORDER STATE 2B';

// CALCULATIONS
export const HCHAIR_SET_CALCULATION = 'HCHAIR SET CALCULATION 2B';
export const HCHAIR_SET_CALCULATION_FORM = 'HCHAIR SET CALCULATION FORM 2B';
export const HCHAIR_UPDATE_CALCULATION_FORM = 'HCHAIR UPDATE CALCULATION FORM 2B';
export const HCHAIR_SET_CALCULATION_LIST = 'HCHAIR SET CALCULATION LIST 2B';
export const HCHAIR_SET_CALCULATION_DETAILS = 'HCHAIR SET CALCULATION DETAILS 2B';
export const HCHAIR_RESET_CALCULATION_STATE = 'HCHAIR RESET CALCULATION STATE 2B';
export const HCHAIR_RESET_CALCULATION_DETAILS = 'HCHAIR RESET CALCULATION DETAILS 2B';

// INHOUSE
export const HCHAIR_SET_INHOUSE = 'HCHAIR SET INHOUSE 2B';
export const HCHAIR_SET_INHOUSE_FORM = 'HCHAIR SET INHOUSE FORM 2B';
export const HCHAIR_UPDATE_INHOUSE_FORM = 'HCHAIR UPDATE INHOUSE FORM 2B';

export const HCHAIR_SET_INHOUSE_LIST = 'HCHAIR SET INHOUSE LIST 2B';
export const HCHAIR_SET_INHOUSE_DETAILS = 'HCHAIR SET INHOUSE DETAILS 2B';