export default {
  MERCHANTS: '/hapichair/merchants',
  ADD_MERCHANT: '/hapichair/merchants/new',
  EDIT_MERCHANT: '/hapichair/merchants/edit',
  ORDERS: '/hapichair/orders',
  CATEGORIES: '/hapichair/categories',
  EDIT_SUB_CATEGORY: '/hapichair/categories/edit',
  ADD_CATEGORY: '/hapichair/categories/new',
  EDIT_CATEGORY: '/hapichair/categories/edit',
  MEMBERS: '/hapichair/members',
  ADD_MEMBER: '/hapichair/members/new',
  EDIT_MEMBER: '/hapichair/members/edit',
  PRODUCTS: '/hapichair/products',
  ADD_PRODUCT: '/hapichair/products/new',
  EDIT_PRODUCT: '/hapichair/products/edit',
  CALCULATIONS: '/hapichair/calculations',
  ADD_CALCULATION: '/hapichair/calculations/new',
  EDIT_CALCULATION: '/hapichair/calculations/edit',
  INHOUSE: '/hapichair/inhouse',
  ADD_INHOUSE: '/hapichair/inhouse/new',
  EDIT_INHOUSE: '/hapichair/inhouse/edit',
};
